### ISSUE TITLE
Annual Projection of Population

### ISSUE THREAD

**Issue by csglui** [PPgp/bayesPop#31]
Hi,

Is it possible to obtain the figure of annual projection of population? At this moment, it seems that only the figures of projected population for every five years can be obtained.

Thank you.

**Comment by hanase** [comment]
At the moment bayesPop generates population projections for 5-year time intervals only. As a workaround, one could obtain 1-year projections by interpolating each population trajectory and then deriving quantiles from the interpolated set.

**Comment by csglui** [comment]
Thank you very much.
