### ISSUE TITLE
Population Projection with External Data

### ISSUE THREAD

**Issue by csglui** [PPgp/bayesPop#32]
Hello! It seems that the package bayesPop can project population other than UN dataset. Any examples that can demonstrate this feature?

Thanks in advance.

**Comment by hanase** [comment]
If you look at the help file for `pop.predict`, each of the items in the `inputs` argument has the corresponding default dataset written in brackets. You can use that as a template for your data. 

Say, you want to generate predictions for China and you want to use your own male mortality rates. Then get the default dataset [mxM] and save it in a file:
```
data(mxM, package = "wpp2019")
write.table(mxM, file = "mymxM.txt", sep = "\t", row.names = FALSE)
# or extract data only for China
write.table(subset(mxM, country_code == 156), 
    file = "mymxM.txt", sep = "\t", row.names = FALSE)
```
You can then use this file as a template for your own data. To run the prediction, do 
```
pred <- pop.predict(countries = 156, inputs = list(mxM = "mymxM.txt"))
```
You can do the same with most of the `inputs` items.

**Comment by csglui** [comment]
Thanks for your reply. 

Since I know that the simulation requires that the net migration is zero in the world, do I need to replace the corresponding population data In the txt file by my country? Or, the txt file contains the population data of my country only? 

Thanks again!

**Comment by hanase** [comment]
The txt file should contain all countries for which projection is generated. If `pop.predict()` runs for all countries, then each txt file in the `inputs` argument should contain data for all countries.

**Comment by csglui** [comment]
Since I am interested in the population projection of some countries only, I will include the data of those countries only.

Thanks.

**Comment by csglui** [comment]
After I have tried my own data, the sampling period is slightly different from the one by UN source. When I import my male and female population data into the function pop.predict() and run the population projection again, the following error messages were generated:

**Error in get.country.inputs(country, inp, nr.traj, UNlocations[country.idx,  : 
  Mismatch in projection periods of TFR and the target projection years.**

Here are code used in the population projection:

sim.dir.pop <- paste0(basepath,'pop_project_HK')
pop.pred <- pop.predict(present.year=2015,
                        wpp.year=2017,
                        output.dir=sim.dir.pop, 
                        input=list(popM=paste0(basepath, 'popM.txt'), 
                                   popF=paste0(basepath, 'popF.txt'), 
                                   tfr.sim.dir=sim.dir.tfr,
                                   e0F.sim.dir=sim.dir.e0, e0M.sim.dir="joint_"),
                        keep.vital.events=TRUE, verbose=TRUE)

Any problem that I need to fix?

Thanks in advance.

**Comment by hanase** [comment]
It's hard to say without having access to the inputs. Things to check are:
* was the simulation in sim.dir.tfr also generated with present.year=2015 (it's not the default in bayesTFR)
* the same for sim.dir.e0
* do the datasets in popM.txt and popF.txt contain the column 2015

**Comment by csglui** [comment]
Actually, in the directory sim.dir.tfr, I execute the functions run.tfr.mcmc() and run.tfr3.mcmc() with the settings present.year=2020, wpp.year=2019.

The same settings of present.year and wpp.year in sim.dir.e0 are the same as those in sim.dir.tfr.

The datasets popM.txt and popF.txt contain the column of year 2015.

Do I rerun the results of sim.dir.tfr and sim.dir.e0 with the setting present.year=2015?

Thanks.

**Comment by hanase** [comment]
Yes. If probabilistic inputs for TFR and e0 are used, then the present_year needs to match. The wpp.year argument can be 2019 in all cases, including pop.predict().

**Comment by csglui** [comment]
Thansk for your help.

1. Actually, my files popM.txt and popF.txt contain the columns from 1961 to 2019.  Now, I am not using the probabilistic inputs for TFR and e0 and use the argument present_year=2019, the function pop.predict() generates two columns of 2020 in the projection output. Which column is the correct output? 

2. On the other hand, when present_year=2015 is used, the function pop.predict() generates the columns for 2015, 2020, 2025, ... It seems that the column for 2015 stores the observed values of population.

3. Also, when I used the summary() method is used in the case of present_year=2015, the quantiles of projected population in 2013, 2018, 2023, .... are produced. When I look into the pop.predict$quantilesM, pop.predict$quantilesF, pop.predict$quantilesMage and pop.predict$quantilesFage, the columns 2015, 2020, 2025,..., are produced. Any discrepency in both sets of output?

4. Also, when the nr.traj=1000, it seems that only 3 trajectories are generated. Is it possible to generate more trajectories?

5. If the probabilistic inputs for TFR and e0 are not used during population projection, does it mean that the values of TFR and e0 are extracted from UN results?

6. Last but not th least, if I want to use the probabilistic inputs for TFR and e0, do I need to re-run the simulation results for TFR and e0 with present_year = 2015 in my case?

Thanks in advance.

**Comment by hanase** [comment]
1.-2. The function tries to snap to 5-year intervals, so your observed 2019 is snapped into 2020, but since 2019 < 2020, it also tries to predict for 2020. If you want to predict for 2020, you need to give it 2015 as the last observed year. And the last observed will be the first column in the prediction.

3. In the final prediction object there are some quantities that are measured in the middle of the interval, while population is measured at the end of the interval. The summary function is reused for all of them, and thus, it's using the middle of the interval. But for population it should be interpreted as the end of the 5-year interval.

4. If you are not using probabilistic inputs, you only get 3 trajectories at most, one for the medians TFR and e0 and two for the low and high variants of TFR. You need to use probabilistic TFR and/or e0 in order to get more trajectories.

5. Yes.

6. Yes.
